spring.application.name=GestionAcces
server.servlet.context-path=/visteonS

#http://localhost:8080/visteonS/swagger-ui/index.html
spring.jpa.properties.hibernate.format_sql=true

#spring.datasource.url= jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=visteonDataBase
#spring.datasource.username=sa
#spring.datasource.password=visteon123

#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServerDialect
#spring.jpa.hibernate.ddl-auto= update

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/visteonDataBase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Hibernate Dialect for MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.event.merge.entity_copy_observer=allow

# HikariCP Connection Pooling (optional)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# JWT Configuration
jwt.secret=39aa5155436d1c99a2c20fdbaa6eedc3c65c880eab03e9d87c44821b3ec594b6
jwt.expiration=86400000

spring.jackson.time-zone=UTC
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mariemhabouria00@gmail.com

spring.mail.password=mxid sixg cdpi ylhs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


report.storage.path=./reports